version: '3.1'

services:
  wordpress:
    image: wordpress
    ports:
      - "127.0.0.1:8890:80"
    env_file:
      - .env.wp
    volumes:
      - wordpress_data:/var/www/html
      - ../../:/var/www/html/wp-content/themes/astra
    depends_on:
      - mysql

  cli:
    privileged: true
    image: wordpress:cli
    user: root
    volumes:
      - wordpress_data:/var/www/html
      - ../../:/var/www/html/wp-content/themes/astra
    env_file:
      - .env.wp
    depends_on:
      - mysql
      - wordpress
    command: tail -f /dev/null

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test

  wordpress:
    depends_on:
    - mysql
    image: hardeepasrani/pirate-brewery
    ports:
    - 8080:80
    privileged: true
    volumes:
    - ~/${WP_CORE_STASH:-wp-core}:/var/www/html/
    - .:/var/www/html/wp-content/themes/astra/
    restart: always
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_ROOT_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1

volumes:
  wordpress_data:
