name: CI

# Run the deployment only when code is committed to the branch.
on:
  pull_request:
      branches:
      - next-release
      - milestones
      - release-candidate
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get npm cache directory
      id: npm-cache
      run: echo "::set-output name=dir::$(npm config get cache)"

    - name: Configure npm cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: npm install, build
      run: |
        npm install

    - name: Start Docker environment
      run: npm run env:start
      env:
        COMPOSE_INTERACTIVE_NO_CLI: true

    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        # Any JS files anywhere within a dist directory:
        pattern: "{assets/**/**/*.js,assets/**/**/*.css}"

        # Always ignore SourceMaps and node_modules:
        exclude: "{**/*.map,**/node_modules/**}"
        build-script: "dynamic-css"

    - name: Stop Docker environment
      run: npm run env:stop
      if: always()
      env:
        COMPOSE_INTERACTIVE_]NO_CLI: true
